server.port: 8000

spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/camunda?characterEncoding=UTF-8
  username: camunda
  password: camunda

camunda.bpm:

  admin-user:
    id: 'admin'
    password: 'admin'

  filter:
    create: All tasks

  webapp:
    application-path: '/'

spring.web.resources.static-locations:
  - 'file:src/main/resources/static/'
  - 'classpath:/static/'

spring.mvc.pathmatch.matching-strategy: ant_path_matcher
