spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/camunda?characterEncoding=UTF-8
  username: camunda
  password: camunda

spring.jpa:
  properties.hibernate.format_sql: true
  #show-sql: true

camunda.bpm:

  admin-user:
    id: 'admin'
    password: 'admin'

  filter:
    create: All tasks
